### PR TITLE
SG-29875 Update Cryptography

### PR DESCRIPTION
**Pull request by carlos-villavicencio-adsk**
Huge PR to update essentially just [one line of code](https://github.com/pyca/cryptography/commit/d6951dca25de45abd52da51b608055371fbcde4e#diff-b81ebda89021aab11aceb5d95cf253b81f9dcdf630468c0483af411cc5005662L159) from cryptography 39.0.1

- resolves #121 
- resolves #122 
- resolves #123 
- resolves #124
- resolves #125 
- Upgrade packages

## Checklist

- [x] pip install -U cryptography==39.0.1 -t resources/python/bin/3.9/mac (intel)
- [x] pip install -U cryptography==39.0.1 -t resources/python/bin/3.7/mac (intel)
- [x] pip install -U cryptography==39.0.1 -t resources/python/bin/3.9/win
- [x] pip install -U cryptography==39.0.1 -t resources/python/bin/3.7/win
- [x] pip install -U cryptography==39.0.1 -t resources/python/bin/3.9/linux
- [x] pip install -U cryptography==39.0.1 -t resources/python/bin/3.7/linux

### CODE REVIEW

**Comment by carlos-villavicencio-adsk** [comment]
Note:
As seen in this [CI run](https://dev.azure.com/shotgun-ecosystem/Toolkit/_build/results?buildId=8885&view=logs&j=7f33e5bd-7764-5d8a-ba2e-506e078b9c3f&t=793c0a09-28bd-56f2-aab1-5963406992f2):

```
E   ImportError: dlopen(/Users/runner/work/1/s/resources/python/bin/3.7/mac/_cffi_backend.cpython-37m-darwin.so, 0x0002): tried: '/Users/runner/work/1/s/resources/python/bin/3.7/mac/_cffi_backend.cpython-37m-darwin.so' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))
```

Included Shared Objects are originally part of Intel architecture (x86_64). However, installing packages on an M1 can cause the above issue.

**Comment by geffrak** [comment]
@carlos-villavicencio-adsk I believe you can use ShotGrid Desktop's desktop-package python to run it in x86_64

**Comment by carlos-villavicencio-adsk** [comment]
Good call

> @carlos-villavicencio-adsk I believe you can use ShotGrid Desktop's desktop-package python to run it in x86_64

**Review by julien-lang — APPROVED** [review]
LGTM!

**Comment by geffrak** [comment]
When do you plan to merge this @carlos-villavicencio-adsk? This is affecting ShotGrid Create.

**Comment by carlos-villavicencio-adsk** [comment]
Update: This already passed QA on macOS. Windows is in progress. Do you want me to merge it anyways @geffrak ?

I'm pretty sure we won't find anything weird.

**Pull request merged**
